version: 2

models:
  - name: Q_EXAMPLE
    description: example
    columns:
      - name: EXAMPLE_PK
      - name: ID
      - name: TIMESTAMP
      - name: PRODUCT_ID
      - name: DT_DATAQUALITY
      - name: ROW_NUM
