version: 2

sources:
  - name: RAW
    loader: IngestPipeline
    description: Source DB from PostgreSQL
    tables:
      - name: RAW_EXAMPLE

models:
  - name: ST_EXAMPLE
    description: from raw_customer
    columns:
      - name: EXAMPLE_PK
      - name: ID
      - name: ACCOUNT_ID
      - name: TIMESTAMP
      - name: PRODUCT_ID
      - name: NAME
      - name: RECORD_INSERTED_IN_STAGING_DATAQUALITY_AT
