version: 2

sources:
  - name: RAW
    description: Source DB from PostgreSQL
    tables:
      - name: RAW_EXAMPLE

models:
  - name: ST_EXAMPLE
    description: from raw_customer
    columns:
      - name: EXAMPLE_PK
      - name: ID
      - name: TIMESTAMP
      - name: PRODUCT_ID
